const emojiKeywords = {
  "😊": ["happy", "smile", "joy", "glad", "pleased", "cheerful", "delighted"],
  "😄": ["happy", "smile", "joy", "laugh", "grin", "amused", "pleased"],
  "😂": ["laugh", "funny", "amused", "hilarious", "cry", "laughing", "tears"],
  "🤣": ["laugh", "funny", "hilarious", "amused", "rolling", "floor", "joke"],
  "😍": [
    "love",
    "heart",
    "beautiful",
    "gorgeous",
    "attractive",
    "adorable",
    "cute",
  ],
  "❤️": ["love", "heart", "like", "care", "passion", "romance", "affection"],
  "🔥": ["fire", "hot", "trending", "popular", "amazing", "awesome", "lit"],
  "✨": [
    "star",
    "sparkle",
    "magic",
    "shiny",
    "special",
    "wonderful",
    "brilliant",
  ],
  "💯": [
    "perfect",
    "full",
    "hundred",
    "excellent",
    "complete",
    "total",
    "awesome",
  ],
  "👍": ["like", "agree", "ok", "good", "great", "thumbs", "up", "approve"],
  "🎉": ["celebrate", "party", "birthday", "fun", "event", "festival", "happy"],
  "😢": [
    "sad",
    "cry",
    "tears",
    "upset",
    "disappointed",
    "heartbroken",
    "sorrow",
  ],
  "😭": ["sad", "cry", "sobbing", "tears", "emotional", "upset", "heartbroken"],
  "😡": [
    "angry",
    "mad",
    "furious",
    "upset",
    "irritated",
    "annoyed",
    "frustrated",
  ],
  "😠": ["angry", "mad", "annoyed", "frustrated", "irritated", "displeased"],
  "❤️": ["love", "heart", "like", "care", "passion", "romance", "affection"],
  "💕": ["love", "heart", "like", "care", "passion", "romance", "affection"],
  "💔": ["broken", "heart", "sad", "hurt", "pain", "loss", "breakup"],
  "🥺": ["sad", "puppy", "eyes", "begging", "cute", "pleading", "emotional"],
  "😬": ["nervous", "awkward", "uncomfortable", "tense", "anxious", "worried"],
  "😨": [
    "scared",
    "afraid",
    "fear",
    "nervous",
    "worried",
    "anxious",
    "terrified",
  ],
  "😰": ["anxious", "worried", "scared", "stressed", "nervous", "afraid"],
  "😱": ["scream", "shocked", "terrified", "scared", "horror", "surprised"],
  "😮": ["surprised", "shocked", "amazed", "astonished", "wow", "speechless"],
  "😲": ["surprised", "shocked", "amazed", "astonished", "wow", "stunned"],
  "🤔": ["think", "ponder", "question", "wonder", "consider", "reflect"],
  "😏": ["smirk", "sly", "playful", "flirt", "mischievous", "amused"],
  "😒": ["unamused", "annoyed", "irritated", "bored", "fed up", "displeased"],
  "😔": ["sad", "disappointed", "upset", "heartbroken", "regret", "sorrow"],
  "😌": ["relieved", "peaceful", "calm", "content", "relaxed", "tranquil"],
  "😤": ["frustrated", "annoyed", "irritated", "impatient", "fed up", "mad"],
  "😣": ["pain", "struggle", "difficulty", "effort", "persevere", "challenge"],
  "😫": ["tired", "exhausted", "stressed", "overwhelmed", "burnt out"],
  "😴": ["sleep", "tired", "bored", "sleepy", "rest", "nap", "bedtime"],
  "😎": ["cool", "stylish", "confident", "attractive", "hip", "trendy"],
  "🥳": ["party", "celebrate", "fun", "birthday", "festive", "joy", "happy"],
  "😇": ["angel", "good", "innocent", "sweet", "pure", "holy", "blessed"],
  "🤗": ["hug", "love", "caring", "warm", "affection", "kindness", "embrace"],
  "🤩": ["starstruck", "excited", "amazed", "wow", "impressed", "speechless"],
  "🤯": ["mindblown", "shocked", "amazed", "wow", "incredible", "unbelievable"],
  "🤪": ["crazy", "silly", "fun", "wild", "goofy", "zany", "wacky"],
  "🥰": ["love", "cute", "sweet", "heart", "affection", "care", "adorable"],
  "😘": ["kiss", "love", "cute", "affection", "sweet", "heart", "romance"],
  "😗": ["kiss", "whistle", "cute", "innocent", "sweet", "affection"],
  "😙": ["kiss", "love", "sweet", "happy", "affection", "cute", "romance"],
  "😚": ["kiss", "love", "sweet", "affection", "cute", "romance", "happy"],
  "☺️": ["smile", "happy", "pleased", "content", "relaxed", "gentle"],
  "😸": ["cat", "smile", "happy", "cute", "playful", "feline", "pet"],
  "😺": ["cat", "smile", "happy", "cute", "playful", "feline", "pet"],
  "😻": ["cat", "love", "cute", "adorable", "feline", "pet", "heart"],
  "😽": ["cat", "kiss", "love", "cute", "feline", "pet", "affection"],
  "🙈": ["monkey", "hiding", "shy", "silly", "see", "hear", "speak"],
  "🙉": ["monkey", "hiding", "shy", "silly", "hear", "see", "speak"],
  "🙊": ["monkey", "hiding", "shy", "silly", "speak", "see", "hear"],
  "🐶": ["dog", "pet", "puppy", "canine", "loyal", "cute", "animal"],
  "🐱": ["cat", "pet", "kitten", "feline", "cute", "animal", "domestic"],
  "🐭": ["mouse", "cute", "small", "rodent", "animal", "pest", "tiny"],
  "🐹": ["hamster", "pet", "cute", "small", "rodent", "animal", "fluffy"],
  "🐰": ["rabbit", "bunny", "cute", "easter", "animal", "fluffy", "small"],
  "🦊": ["fox", "cunning", "wild", "animal", "orange", "forest", "cute"],
  "🐻": ["bear", "teddy", "cute", "animal", "brown", "wild", "hibernation"],
  "🐼": ["panda", "bear", "cute", "animal", "black", "white", "chinese"],
  "🐨": [
    "koala",
    "cute",
    "animal",
    "australian",
    "marsupial",
    "tree",
    "fluffy",
  ],
  "🐯": ["tiger", "wild", "animal", "stripe", "big cat", "predator", "orange"],
  "🦁": ["lion", "king", "animal", "wild", "big cat", "predator", "mane"],
  "🐮": ["cow", "animal", "farm", "milk", "bovine", "cattle", "dairy"],
  "🐷": ["pig", "animal", "farm", "cute", "pork", "swine", "oink"],
  "🐸": ["frog", "animal", "amphibian", "green", "jump", "pond", "rain"],
  "🐵": ["monkey", "animal", "primate", "wild", "jungle", "playful", "banana"],
  "🐔": ["chicken", "bird", "farm", "poultry", "egg", "animal", "poultry"],
  "🐧": ["penguin", "bird", "antarctic", "cute", "animal", "cold", "polar"],
  "🐦": ["bird", "animal", "wing", "fly", "feather", "sky", "nature"],
  "🐤": ["chick", "baby", "bird", "cute", "yellow", "animal", "spring"],
  "🐣": ["hatch", "baby", "bird", "easter", "spring", "new", "life"],
  "🐥": ["chick", "baby", "bird", "cute", "yellow", "animal", "spring"],
  "🦆": ["duck", "bird", "animal", "waterfowl", "quack", "pond", "farm"],
  "🦅": ["eagle", "bird", "predator", "fly", "sky", "wild", "freedom"],
  "🦉": ["owl", "bird", "wise", "night", "animal", "hunt", "knowledge"],
  "🦇": ["bat", "animal", "night", "fly", "halloween", "spooky", "wing"],
  "🐺": ["wolf", "animal", "wild", "predator", "pack", "moon", "canine"],
  "🐗": ["boar", "wild", "pig", "animal", "forest", "tusk", "hunt"],
  "🐴": ["horse", "animal", "farm", "ride", "equine", "gallop", "stable"],
  "🦄": ["unicorn", "magic", "mythical", "horse", "rainbow", "fantasy", "cute"],
  "🐝": ["bee", "bug", "insect", "honey", "sting", "yellow", "buzz"],
  "🪱": ["worm", "bug", "animal", "soil", "garden", "slither", "earth"],
  "🐛": ["caterpillar", "bug", "insect", "garden", "leaf", "green", "crawling"],
  "🦋": [
    "butterfly",
    "insect",
    "beautiful",
    "garden",
    "fly",
    "colorful",
    "wing",
  ],
  "🐌": ["snail", "slow", "animal", "garden", "shell", "crawl", "rain"],
  "🐞": ["ladybug", "insect", "bug", "garden", "cute", "red", "ladybird"],
  "🐜": ["ant", "insect", "bug", "small", "colony", "worker", "crawling"],
  "🪰": ["fly", "bug", "insect", "annoying", "buzz", "pest", "wing"],
  "🪲": ["beetle", "bug", "insect", "hard", "shell", "crawling", "animal"],
  "🪳": ["roach", "bug", "insect", "pest", "cockroach", "crawling", "dark"],
  "🐢": ["turtle", "slow", "animal", "shell", "reptile", "aquatic", "green"],
  "🐍": ["snake", "reptile", "danger", "poison", "slimy", "wild", "dangerous"],
  "🦎": ["lizard", "reptile", "crawling", "animal", "scaly", "warm", "desert"],
  "🦖": [
    "dinosaur",
    "extinct",
    "reptile",
    "prehistoric",
    "giant",
    "fossil",
    "t rex",
  ],
  "🦕": [
    "dinosaur",
    "extinct",
    "reptile",
    "prehistoric",
    "giant",
    "fossil",
    "sauropod",
  ],
  "🐙": [
    "octopus",
    "sea",
    "animal",
    "tentacle",
    "ocean",
    "intelligent",
    "underwater",
  ],
  "🦑": ["squid", "sea", "animal", "tentacle", "ocean", "underwater", "deep"],
  "🦐": ["shrimp", "seafood", "animal", "ocean", "small", "pink", "crustacean"],
  "🦞": [
    "lobster",
    "seafood",
    "animal",
    "ocean",
    "red",
    "crustacean",
    "luxury",
  ],
  "🐠": ["fish", "aquatic", "ocean", "animal", "swim", "pet", "colorful"],
  "🐟": ["fish", "aquatic", "ocean", "animal", "swim", "food", "seafood"],
  "🐡": ["pufferfish", "fish", "ocean", "animal", "cute", "spiky", "swim"],
  "🐬": ["dolphin", "ocean", "animal", "smart", "playful", "marine", "swim"],
  "🐳": ["whale", "ocean", "animal", "huge", "marine", "deep", "endangered"],
  "🐋": ["whale", "ocean", "animal", "huge", "marine", "deep", "mammal"],
  "🦈": ["shark", "ocean", "predator", "dangerous", "fish", "marine", "teeth"],
  "🐊": [
    "crocodile",
    "reptile",
    "dangerous",
    "animal",
    "predator",
    "swamp",
    "teeth",
  ],
  "🐅": ["tiger", "animal", "wild", "predator", "stripe", "big cat", "orange"],
  "🐆": ["leopard", "animal", "wild", "predator", "spots", "big cat", "fast"],
  "🦓": [
    "zebra",
    "animal",
    "wild",
    "stripe",
    "african",
    "horse",
    "black white",
  ],
  "💻": [
    "computer",
    "code",
    "programming",
    "tech",
    "digital",
    "screen",
    "laptop",
  ],
  "⌨️": ["keyboard", "typing", "code", "computer", "tech", "input", "keys"],
  "🖥️": ["computer", "screen", "monitor", "tech", "desktop", "display", "work"],
  "🖱️": ["mouse", "computer", "tech", "click", "input", "device", "scroll"],
  "🖨️": ["printer", "print", "computer", "tech", "office", "paper", "document"],
  "📱": ["phone", "mobile", "smartphone", "tech", "call", "apple", "android"],
  "📲": [
    "phone",
    "mobile",
    "smartphone",
    "tech",
    "call",
    "notification",
    "message",
  ],
  "💾": ["disk", "save", "computer", "tech", "storage", "floppy", "data"],
  "💿": ["cd", "disc", "music", "data", "storage", "tech", "dvd"],
  "📀": ["dvd", "disc", "movie", "data", "storage", "tech", "video"],
  "📡": [
    "satellite",
    "signal",
    "tech",
    "space",
    "communication",
    "broadcast",
    "dish",
  ],
  "🛰️": [
    "satellite",
    "space",
    "tech",
    "orbit",
    "communication",
    "science",
    "probe",
  ],
  "🚀": ["rocket", "space", "tech", "launch", "science", "astronaut", "mars"],
  "🛸": [
    "ufo",
    "alien",
    "space",
    "flying",
    "tech",
    "mystery",
    "extraterrestrial",
  ],
  "🤖": [
    "robot",
    "tech",
    "artificial",
    "automation",
    "machine",
    "future",
    "cyber",
  ],
  "👾": ["alien", "game", "space", "retro", "arcade", "monster", "tech"],
  "💡": ["idea", "light", "bulb", "creative", "think", "solution", "innovate"],
  "🔦": [
    "flashlight",
    "light",
    "dark",
    "camping",
    "emergency",
    "illuminate",
    "search",
  ],
  "🔋": [
    "battery",
    "power",
    "energy",
    "charge",
    "tech",
    "portable",
    "electricity",
  ],
  "🪫": ["battery", "low", "power", "energy", "charge", "tech", "empty"],
  "🧬": ["dna", "science", "biology", "genetic", "gene", "helix", "research"],
  "🔬": [
    "microscope",
    "science",
    "research",
    "laboratory",
    "biology",
    "discover",
    "analyze",
  ],
  "🔭": [
    "telescope",
    "space",
    "science",
    "astronomy",
    "observe",
    "stars",
    "explore",
  ],
  "📷": [
    "camera",
    "photo",
    "picture",
    "photography",
    "memory",
    "instant",
    "shot",
  ],
  "📸": [
    "camera",
    "photo",
    "selfie",
    "picture",
    "photography",
    "instant",
    "shot",
  ],
  "📹": ["video", "camera", "recording", "film", "movie", "vlog", "content"],
  "🎥": [
    "movie",
    "camera",
    "film",
    "video",
    "cinema",
    "director",
    "production",
  ],
  "📽️": ["film", "movie", "projector", "cinema", "video", "reel", "theater"],
  "🎞️": ["film", "movie", "strip", "cinema", "video", "reel", "classic"],
  "📞": [
    "phone",
    "call",
    "telephone",
    "communication",
    "contact",
    "ring",
    "dial",
  ],
  "☎️": [
    "phone",
    "call",
    "telephone",
    "communication",
    "contact",
    "ring",
    "dial",
  ],
  "📟": [
    "pager",
    "communication",
    "vintage",
    "device",
    "notification",
    "message",
  ],
  "📠": [
    "fax",
    "machine",
    "communication",
    "office",
    "document",
    "send",
    "paper",
  ],
  "📺": ["tv", "television", "screen", "show", "movie", "program", "stream"],
  "📻": ["radio", "music", "station", "broadcast", "audio", "podcast", "talk"],
  "🎙️": ["mic", "studio", "record", "audio", "speak", "podcast", "music"],
  "🎚️": [
    "slider",
    "control",
    "mixer",
    "audio",
    "studio",
    "adjust",
    "production",
  ],
  "🎛️": ["knob", "control", "mixer", "audio", "studio", "adjust", "production"],
  "🕰️": ["clock", "time", "vintage", "history", "antique", "hour", "minute"],
  "⌚": [
    "watch",
    "time",
    "wearable",
    "accessory",
    "stylish",
    "digital",
    "analog",
  ],
  "🚗": ["car", "drive", "travel", "vehicle", "auto", "road", "transport"],
  "🚕": ["taxi", "car", "drive", "travel", "cab", "transport", "city"],
  "🚙": ["car", "drive", "travel", "vehicle", "auto", "road", "transport"],
  "🚌": ["bus", "travel", "transport", "vehicle", "commute", "city", "school"],
  "🚎": ["tram", "transport", "city", "vehicle", "travel", "public", "track"],
  "🏎️": ["car", "race", "speed", "motor", "sport", "fast", "formula"],
  "🚓": [
    "police",
    "car",
    "emergency",
    "law",
    "enforcement",
    "safety",
    "patrol",
  ],
  "🚑": [
    "ambulance",
    "emergency",
    "medical",
    "hospital",
    "rescue",
    "health",
    "urgent",
  ],
  "🚒": [
    "firetruck",
    "emergency",
    "fire",
    "rescue",
    "department",
    "water",
    "siren",
  ],
  "🚐": [
    "van",
    "travel",
    "vehicle",
    "transport",
    "adventure",
    "camper",
    "road",
  ],
  "🚛": [
    "truck",
    "transport",
    "freight",
    "delivery",
    "vehicle",
    "road",
    "cargo",
  ],
  "🚜": [
    "tractor",
    "farm",
    "agriculture",
    "vehicle",
    "field",
    "work",
    "harvest",
  ],
  "🛵": ["scooter", "travel", "vehicle", "two", "wheeler", "transport", "city"],
  "🏍️": [
    "motorcycle",
    "vehicle",
    "travel",
    "road",
    "speed",
    "bike",
    "transport",
  ],
  "🚲": [
    "bicycle",
    "bike",
    "exercise",
    "transport",
    "travel",
    "cycle",
    "health",
  ],
  "🚨": [
    "siren",
    "emergency",
    "police",
    "warning",
    "alarm",
    "urgent",
    "danger",
  ],
  "🚔": [
    "police",
    "car",
    "emergency",
    "law",
    "enforcement",
    "safety",
    "patrol",
  ],
  "🚍": ["bus", "travel", "transport", "vehicle", "commute", "city", "school"],
  "🚘": ["car", "drive", "travel", "vehicle", "auto", "road", "transport"],
  "🚖": ["taxi", "car", "drive", "travel", "cab", "transport", "city"],
  "🚡": ["cable", "car", "transport", "ski", "mountain", "tourist", "view"],
  "🚠": ["cable", "car", "transport", "ski", "mountain", "tourist", "view"],
  "🚟": ["suspension", "rail", "transport", "city", "train", "track", "high"],
  "🚃": ["tram", "transport", "city", "vehicle", "travel", "public", "track"],
  "🚋": ["tram", "transport", "city", "vehicle", "travel", "public", "track"],
  "🚞": [
    "mountain",
    "railway",
    "transport",
    "scenic",
    "train",
    "track",
    "tourist",
  ],
  "🚝": ["monorail", "transport", "city", "train", "track", "high", "modern"],
  "🚄": [
    "train",
    "transport",
    "speed",
    "rail",
    "shinkansen",
    "japan",
    "travel",
  ],
  "🚅": [
    "train",
    "transport",
    "speed",
    "rail",
    "shinkansen",
    "japan",
    "travel",
  ],
  "🚈": ["train", "transport", "rail", "city", "commute", "electric", "modern"],
  "🚂": ["train", "transport", "steam", "historic", "rail", "travel", "choo"],
  "✈️": ["plane", "travel", "flight", "airport", "fly", "holiday", "trip"],
  "🛸": [
    "ufo",
    "alien",
    "space",
    "flying",
    "tech",
    "mystery",
    "extraterrestrial",
  ],
  "🚁": [
    "helicopter",
    "travel",
    "fly",
    "vehicle",
    "aircraft",
    "rotor",
    "military",
  ],
  "⛵": ["sailboat", "sail", "travel", "boat", "water", "sailing", "wind"],
  "🚢": ["ship", "cruise", "travel", "boat", "ocean", "voyage", "transport"],
  "🛳️": ["cruise", "ship", "travel", "holiday", "ocean", "voyage", "passenger"],
  "🚤": ["speedboat", "boat", "water", "travel", "speed", "motor", "marine"],
  "🛥️": ["boat", "yacht", "water", "travel", "luxury", "marine", "vessel"],
  "🌍": [
    "earth",
    "world",
    "global",
    "planet",
    "map",
    "travel",
    "international",
  ],
  "🌎": [
    "earth",
    "world",
    "global",
    "planet",
    "map",
    "travel",
    "international",
  ],
  "🌏": [
    "earth",
    "world",
    "global",
    "planet",
    "map",
    "travel",
    "international",
  ],
  "🏔️": [
    "mountain",
    "landscape",
    "nature",
    "peak",
    "hike",
    "snow",
    "adventure",
  ],
  "⛰️": [
    "mountain",
    "landscape",
    "nature",
    "peak",
    "hike",
    "climbing",
    "adventure",
  ],
  "🌋": [
    "volcano",
    "mountain",
    "eruption",
    "lava",
    "fire",
    "nature",
    "dangerous",
  ],
  "🏝️": [
    "island",
    "beach",
    "tropical",
    "paradise",
    "holiday",
    "vacation",
    "ocean",
  ],
  "🌈": ["rainbow", "colorful", "magic", "hope", "lgbt", "beautiful", "sky"],
  "☀️": ["sun", "sunny", "weather", "light", "warm", "summer", "bright"],
  "🌤️": ["sun", "weather", "cloudy", "partly", "sunny", "sky", "warm"],
  "⛅": ["cloud", "weather", "sky", "cloudy", "sun", "overcast", "gray"],
  "🌥️": ["cloud", "weather", "sky", "cloudy", "overcast", "gray", "dark"],
  "☁️": ["cloud", "weather", "sky", "cloudy", "overcast", "gray", "dark"],
  "🌦️": ["rain", "sun", "weather", "shower", "rainbow", "cloud", "sunny"],
  "🌧️": ["rain", "weather", "cloud", "water", "storm", "umbrella", "wet"],
  "⛈️": ["thunder", "storm", "rain", "lightning", "weather", "danger", "power"],
  "🌩️": ["lightning", "storm", "thunder", "energy", "danger", "power", "sky"],
  "🌨️": ["snow", "winter", "cold", "weather", "flake", "freeze", "white"],
  "❄️": ["snow", "winter", "cold", "ice", "flake", "freeze", "weather"],
  "☃️": ["snowman", "snow", "winter", "cold", "weather", "fun", "holiday"],
  "⛄": ["snowman", "snow", "winter", "cold", "weather", "fun", "holiday"],
  "🌬️": ["wind", "weather", "blow", "breeze", "gust", "air", "autumn"],
  "💨": ["wind", "run", "fast", "smoke", "speed", "air", "blow"],
  "🌪️": ["tornado", "storm", "weather", "danger", "spiral", "wind", "disaster"],
  "☔": ["rain", "umbrella", "weather", "wet", "storm", "drops", "shower"],
  "☂️": ["umbrella", "rain", "weather", "wet", "protection", "storm", "shower"],
  "🌊": ["wave", "ocean", "water", "sea", "surf", "flow", "nature"],
  "💧": ["drop", "water", "rain", "liquid", "hydrate", "clean", "tear"],
  "💦": ["sweat", "water", "splash", "rain", "exercise", "drops", "wet"],
  "🌫️": ["fog", "mist", "weather", "cloud", "low", "visibility", "smoke"],
  "🌡️": [
    "thermometer",
    "temperature",
    "weather",
    "hot",
    "cold",
    "health",
    "fever",
  ],
  "🔥": ["fire", "hot", "trending", "popular", "amazing", "awesome", "lit"],
  "💥": [
    "explosion",
    "impact",
    "hit",
    "power",
    "collision",
    "boom",
    "powerful",
  ],
  "⚡": [
    "lightning",
    "energy",
    "power",
    "speed",
    "electricity",
    "fast",
    "thunder",
  ],
  "🌅": [
    "sunrise",
    "morning",
    "sky",
    "beautiful",
    "view",
    "nature",
    "photography",
  ],
  "🌄": [
    "sunrise",
    "morning",
    "sky",
    "mountain",
    "sun",
    "nature",
    "photography",
  ],
  "🌇": [
    "sunset",
    "evening",
    "city",
    "sky",
    "beautiful",
    "nature",
    "photography",
  ],
  "🌆": [
    "sunset",
    "evening",
    "city",
    "sky",
    "beautiful",
    "nature",
    "photography",
  ],
  "🌃": ["night", "city", "sky", "star", "moon", "dark", "beautiful"],
  "🌌": ["milky", "way", "sky", "star", "universe", "space", "photography"],
  "🌉": [
    "bridge",
    "city",
    "night",
    "landmark",
    "photography",
    "architecture",
    "skyline",
  ],
  "🌁": ["fog", "mist", "city", "skyline", "weather", "mood", "photography"],
  "🏙️": [
    "city",
    "buildings",
    "urban",
    "skyline",
    "architecture",
    "downtown",
    "metropolis",
  ],
  "🌃": ["night", "city", "sky", "star", "moon", "dark", "beautiful"],
  "🌠": ["shooting", "star", "night", "wish", "sky", "universe", "magic"],
  "🎇": [
    "fireworks",
    "celebration",
    "night",
    "party",
    "festival",
    "light",
    "colorful",
  ],
  "🎆": [
    "fireworks",
    "celebration",
    "night",
    "party",
    "festival",
    "light",
    "colorful",
  ],
  "🍕": ["pizza", "food", "italian", "cheese", "delicious", "italy", "dinner"],
  "🍔": ["burger", "food", "fast", "meal", "lunch", "hamburger", "snack"],
  "🍟": ["fries", "food", "fast", "snack", "chips", "potato", "sides"],
  "🌮": ["taco", "food", "mexican", "lunch", "dinner", "spicy", "tortilla"],
  "🌯": ["burrito", "food", "mexican", "lunch", "dinner", "wrap", "spicy"],
  "🍗": ["chicken", "food", "meat", "dinner", "poultry", "protein", "meal"],
  "🍖": ["meat", "food", "bone", "barbecue", "grill", "protein", "dinner"],
  "🥩": ["steak", "meat", "food", "grill", "dinner", "beef", "restaurant"],
  "🍣": ["sushi", "food", "japanese", "fish", "raw", "rice", "seafood"],
  "🍤": ["tempura", "food", "japanese", "shrimp", "fried", "seafood", "batter"],
  "🍚": ["rice", "food", "asian", "grain", "meal", "side", "japanese"],
  "🍛": ["curry", "food", "indian", "spicy", "rice", "meal", "asian"],
  "🍜": ["ramen", "food", "japanese", "noodle", "soup", "meal", "hot"],
  "🍝": ["pasta", "food", "italian", "noodle", "dinner", "spaghetti", "italy"],
  "🍠": ["sweet", "potato", "food", "root", "vegetable", "healthy", "side"],
  "🍢": ["oden", "food", "japanese", "skewer", "soup", "winter", "street"],
  "🍥": ["naruto", "fish", "cake", "food", "japanese", "ramen", "topping"],
  "🍦": ["ice", "cream", "food", "dessert", "sweet", "summer", "treat"],
  "🍧": ["shaved", "ice", "dessert", "sweet", "summer", "japanese", "treat"],
  "🍨": ["ice", "cream", "dessert", "sweet", "treat", "summer", "cold"],
  "🍩": ["donut", "dessert", "sweet", "treat", "pastry", "glazed", "breakfast"],
  "🍪": ["cookie", "dessert", "sweet", "treat", "snack", "baked", "chocolate"],
  "🎂": [
    "cake",
    "birthday",
    "dessert",
    "sweet",
    "celebration",
    "party",
    "treat",
  ],
  "🍰": ["cake", "dessert", "sweet", "treat", "pastry", "celebration", "party"],
  "🧁": ["cupcake", "dessert", "sweet", "treat", "pastry", "birthday", "party"],
  "🥧": ["pie", "dessert", "sweet", "treat", "pastry", "baked", "thanksgiving"],
  "🍫": [
    "chocolate",
    "dessert",
    "sweet",
    "treat",
    "candy",
    "delicious",
    "sweet",
  ],
  "🍬": [
    "candy",
    "sweet",
    "treat",
    "dessert",
    "sugar",
    "delicious",
    "childhood",
  ],
  "🍭": [
    "lollipop",
    "candy",
    "sweet",
    "treat",
    "dessert",
    "sugar",
    "childhood",
  ],
  "🍮": [
    "pudding",
    "dessert",
    "sweet",
    "treat",
    "creamy",
    "pastry",
    "japanese",
  ],
  "🍯": ["honey", "sweet", "food", "natural", "bee", "healthy", "spread"],
  "🍼": ["baby", "milk", "food", "bottle", "infant", "feeding", "health"],
  "🥛": ["milk", "drink", "dairy", "healthy", "calcium", "white", "breakfast"],
  "☕": [
    "coffee",
    "drink",
    "morning",
    "caffeine",
    "hot",
    "breakfast",
    "energy",
  ],
  "🍵": ["tea", "drink", "hot", "green", "japanese", "healthy", "relaxation"],
  "🍶": ["sake", "drink", "alcohol", "japanese", "rice", "wine", "spirit"],
  "🍾": [
    "champagne",
    "celebrate",
    "drink",
    "alcohol",
    "party",
    "bubbly",
    "toast",
  ],
  "🍷": ["wine", "drink", "alcohol", "grape", "dinner", "romantic", "cheers"],
  "🍸": ["cocktail", "drink", "alcohol", "party", "bar", "mix", "clubbing"],
  "🍹": [
    "tropical",
    "drink",
    "cocktail",
    "summer",
    "vacation",
    "fruit",
    "refreshing",
  ],
  "🍺": ["beer", "drink", "alcohol", "bar", "party", "pub", "brew"],
  "🍻": [
    "cheers",
    "drink",
    "alcohol",
    "party",
    "celebration",
    "toast",
    "friends",
  ],
  "🥂": [
    "toast",
    "celebrate",
    "drink",
    "alcohol",
    "party",
    "clinking",
    "glasses",
  ],
  "🥃": ["whiskey", "drink", "alcohol", "spirit", "bar", "scotch", "bourbon"],
  "🥤": ["drink", "soda", "cold", "beverage", "fastfood", "refreshment", "cup"],
  "🧃": ["juice", "drink", "beverage", "healthy", "fruit", "kids", "lunch"],
  "🧉": ["mate", "drink", "south", "america", "tea", "herbal", "traditional"],
  "🧊": ["ice", "cube", "cold", "drink", "cool", "freeze", "water"],
  "💰": ["money", "cash", "wealth", "dollar", "rich", "payment", "business"],
  "💵": ["money", "cash", "dollar", "bill", "currency", "payment", "wealth"],
  "💶": ["money", "euro", "cash", "currency", "europe", "payment", "wealth"],
  "💷": ["money", "pound", "cash", "currency", "uk", "payment", "wealth"],
  "💴": ["money", "yen", "cash", "currency", "japan", "payment", "wealth"],
  "💳": ["credit", "card", "payment", "money", "business", "shopping", "bank"],
  "💎": ["diamond", "gem", "jewelry", "luxury", "rich", "engagement", "bling"],
  "💍": [
    "ring",
    "jewelry",
    "marriage",
    "wedding",
    "engagement",
    "gold",
    "diamond",
  ],
  "👗": [
    "dress",
    "fashion",
    "clothing",
    "women",
    "formal",
    "style",
    "wardrobe",
  ],
  "👘": [
    "kimono",
    "japanese",
    "fashion",
    "clothing",
    "traditional",
    "culture",
    "formal",
  ],
  "👔": [
    "tie",
    "formal",
    "business",
    "suit",
    "clothing",
    "professional",
    "office",
  ],
  "👕": [
    "shirt",
    "clothing",
    "t-shirt",
    "fashion",
    "casual",
    "wardrobe",
    "top",
  ],
  "👖": [
    "pants",
    "jeans",
    "clothing",
    "fashion",
    "casual",
    "wardrobe",
    "bottom",
  ],
  "🧥": [
    "coat",
    "jacket",
    "clothing",
    "winter",
    "fashion",
    "outerwear",
    "warm",
  ],
  "🧤": ["gloves", "clothing", "winter", "cold", "hands", "accessory", "warm"],
  "🧣": ["scarf", "clothing", "winter", "warm", "accessory", "fashion", "neck"],
  "🧦": ["socks", "clothing", "fashion", "feet", "warm", "accessory", "wear"],
  "👟": [
    "sneakers",
    "shoes",
    "athletic",
    "sport",
    "casual",
    "fashion",
    "footwear",
  ],
  "👠": ["heels", "shoes", "women", "fashion", "formal", "footwear", "high"],
  "👡": ["sandals", "shoes", "summer", "casual", "beach", "footwear", "women"],
  "👢": ["boots", "shoes", "winter", "fashion", "footwear", "cold", "trendy"],
  "👞": [
    "shoes",
    "formal",
    "business",
    "men",
    "leather",
    "footwear",
    "professional",
  ],
  "🧢": ["hat", "cap", "fashion", "sport", "casual", "accessory", "head"],
  "👒": ["hat", "fashion", "women", "accessory", "elegant", "sun", "beach"],
  "🎩": [
    "top",
    "hat",
    "fashion",
    "formal",
    "accessory",
    "gentleman",
    "elegant",
  ],
  "⛑️": [
    "helmet",
    "safety",
    "construction",
    "protection",
    "head",
    "worker",
    "hard",
  ],
  "👑": ["crown", "royal", "king", "queen", "royalty", "monarch", "luxury"],
  "💄": [
    "lipstick",
    "beauty",
    "makeup",
    "cosmetics",
    "women",
    "fashion",
    "gloss",
  ],
  "💅": ["nail", "polish", "beauty", "spa", "manicure", "women", "accessory"],
  "💇": ["hair", "cut", "salon", "beauty", "barber", "style", "makeover"],
  "💈": ["barber", "shop", "salon", "style", "hair", "cut", "grooming"],
  "🪞": [
    "mirror",
    "beauty",
    "reflection",
    "bathroom",
    "look",
    "vanity",
    "grooming",
  ],
  "🪟": [
    "window",
    "glass",
    "building",
    "architecture",
    "view",
    "room",
    "light",
  ],
  "🛋️": ["sofa", "couch", "furniture", "lounge", "relax", "sitting", "home"],
  "🛏️": ["bed", "sleep", "furniture", "rest", "bedroom", "hotel", "night"],
  "🛁": ["bathtub", "bath", "relax", "bathroom", "spa", "clean", "water"],
  "🚿": ["shower", "bath", "clean", "water", "bathroom", "daily", "fresh"],
  "🚽": [
    "toilet",
    "restroom",
    "bathroom",
    "washroom",
    "wc",
    "facility",
    "plumbing",
  ],
  "🪥": [
    "toothbrush",
    "dental",
    "brush",
    "health",
    "bathroom",
    "oral",
    "hygiene",
  ],
  "🪒": ["razor", "shave", "grooming", "men", "barber", "personal", "care"],
  "🧴": [
    "lotion",
    "cream",
    "moisturizer",
    "beauty",
    "skin",
    "care",
    "sunscreen",
  ],
  "🧵": ["needle", "thread", "sewing", "craft", "fabric", "tailor", "repair"],
  "🧶": ["yarn", "knit", "crochet", "craft", "wool", "hobby", "warm"],
  "🪡": ["needle", "sewing", "craft", "tailor", "repair", "fabric", "thread"],
  "🪢": ["knot", "rope", "tie", "sail", "craft", "secure", "bind"],
  "💪": ["muscle", "strong", "fit", "gym", "workout", "power", "health"],
  "🦵": ["leg", "muscle", "body", "sport", "anatomy", "strength", "exercise"],
  "🦶": ["foot", "body", "feet", "anatomy", "movement", "steps", "walking"],
  "🧠": [
    "brain",
    "smart",
    "intelligence",
    "mind",
    "thinking",
    "knowledge",
    "smart",
  ],
  "🫀": ["heart", "organ", "health", "anatomy", "medical", "blood", "pump"],
  "🫁": [
    "lungs",
    "breath",
    "organ",
    "health",
    "anatomy",
    "medical",
    "respiratory",
  ],
  "🦷": ["tooth", "dental", "health", "mouth", "dentist", "oral", "smile"],
  "🦴": ["bone", "skeleton", "anatomy", "medical", "structure", "body", "dog"],
  "👁️": ["eye", "vision", "sight", "look", "see", "optometry", "observe"],
  "👂": ["ear", "listen", "hear", "sound", "music", "loud", "hearing"],
  "👃": ["nose", "smell", "breathe", "scent", "olfactory", "face", "anatomy"],
  "👄": ["mouth", "speak", "talk", "lips", "voice", "kiss", "mouth"],
};

module.exports = emojiKeywords;
